# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.SlugField(unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Miniature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.SlugField(unique=True)),
                ('name', models.CharField(default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='images')),
                ('miniature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpmpb.Miniature')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='photosession',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rpmpb.Tag'),
        ),
        migrations.AddField(
            model_name='miniature',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rpmpb.Tag'),
        ),
        migrations.AddField(
            model_name='album',
            name='miniatures',
            field=models.ManyToManyField(blank=True, to='rpmpb.Miniature'),
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rpmpb.Tag'),
        ),
    ]
