# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpmpb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albums',
            field=models.ManyToManyField(blank=True, null=True, related_name='_album_albums_+', to='rpmpb.Album'),
        ),
    ]
