# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpmpb', '0002_auto_20170710_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='album',
            name='miniatures',
            field=models.ManyToManyField(blank=True, to='rpmpb.Miniature'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rpmpb.Tag'),
        ),
    ]
